include dgprtl/common.mk

dblcdintf_extra_srcs=dgprtl/latchingcounter.v

all: dblcdintf.vcd hdmiintf.vcd

doit:
	LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libfreetype.so.6 ~/gowinshit/IDE/bin/gw_sh build.tcl
